# Generated by Django 3.2.3 on 2021-06-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SonicRes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testupload',
            name='filex',
            field=models.FileField(upload_to='test'),
        ),
    ]
