# Generated by Django 3.2.3 on 2021-07-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SonicRes', '0002_alter_testupload_filex'),
    ]

    operations = [
        migrations.AddField(
            model_name='testupload',
            name='title',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
