# Generated by Django 3.2.3 on 2021-07-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SonicRes', '0003_testupload_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='testupload',
            name='shortUrl',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
